# Site wide configuration

title:            oshchip.org
locale:           en_US
modified:         2016-02-11
#url:              http://localhost:4000
url:              http://oshchip.org

encoding: UTF-8

# Jekyll configuration

###  removed trailing slash, links must include .html , and will display with .html
permalink:   /:title
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: OSHChip
  avatar: OSHChip_Avatar.jpg
  bio: "32 bit Cortex-M0 with 256 KB Flash, 32KB RAM, and Bluetooth LE radio"
  email: philip@oshchip.org
  disqus-shortname: oshchiporg
  twitter: PhilipFreidin
  github: oshchip
  flickr: 
  facebook: #username
  google:
    plus: #username
    analytics:
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
